lws/cook/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FieldList
from wtforms.validators import DataRequired, ValidationError

from lws.models import Menu, Dish, Ingredient

class IngredientForm(FlaskForm):
    ingredient_name = StringField('Ingredient', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_ingredient_name(self, ingredient_name):
        ingredient = Ingredient.query.filter_by(name=ingredient_name.data).first()
        if ingredient is not None:
            raise ValidationError('{0} is already in the system.'.format(ingredient_name.data))

class DishForm(FlaskForm):
    dish_name = StringField('Dish', validators=[DataRequired()])
    ingredients = FieldList(StringField('Ingredient', validators=[DataRequired()]), min_entries=1)
    add_entry = SubmitField('One more ingredient')
    pop_entry = SubmitField('remove last ingredient')
    submit = SubmitField('Submit')

    def validate_dish_name(self, dish_name):
        dish = Dish.query.filter_by(name=dish_name.data).first()
        if dish is not None:
            raise ValidationError('{0} is already in the system.'.format(dish_name.data))

class MenuForm(FlaskForm):
    menu_name = StringField('Menu', validators=[DataRequired()])
    dishes = FieldList(StringField('Dish', validators=[DataRequired()]), min_entries=1)
    add_entry = SubmitField('One more dish')
    pop_entry = SubmitField('remove last dish')
    submit = SubmitField('Submit')

    def __init__(self, original_menu_name, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)
        self.original_menu_name = original_menu_name

    def validate_menu_name(self, menu_name):
        if menu_name.data != self.original_menu_name:
            menu = Menu.query.filter_by(name=menu_name.data).first()
            if menu is not None:
                raise ValidationError('{0} is already in the system.'.format(menu_name.data))

lws/cook/__init__.py
from flask import Blueprint

bp = Blueprint('cook', __name__)

from lws.cook import routes

lws/cook/routes.py
from flask import jsonify
from flask_login import login_required
from flask import flash, redirect, url_for, render_template, request

from lws import lws_db
from lws.models import Menu, Dish, Ingredient
from lws.cook import bp
from lws.cook.forms import MenuForm, DishForm, IngredientForm

@bp.route('/add_ingredient', methods=['GET', 'POST'])
@login_required
def add_ingredient():
    form = IngredientForm()
    if form.validate_on_submit():
        ingredient = Ingredient(name=form.ingredient_name.data)
        lws_db.session.add(ingredient)
        lws_db.session.commit()
        flash('New ingredient is added.')
        return redirect(url_for('cook.add_ingredient'))

    page = request.args.get('page', 1, type=int)
    ingredients = Ingredient.query.paginate(page, 25, False)

    next_url = None
    if ingredients.has_next:
        next_url = url_for('cook.add_ingredient', page=ingredients.next_num)
    prev_url = None
    if ingredients.has_prev:
        prev_url = url_for('cook.add_ingredient', page=ingredients.prev_num)

    return render_template('cook/add_ingredient.html', 
                            title='Ingredient', 
                            form=form,
                            ingredients=ingredients.items,
                            next_url=next_url,
                            prev_url=prev_url)

@bp.route('/add_dish', methods=['GET', 'POST'])
@login_required
def add_dish():
    page = request.args.get('page', 1, type=int)
    dishes = Dish.query.paginate(page, 25, False)

    next_url = None
    if dishes.has_next:
        next_url = url_for('cook.add_dish', page=dishes.next_num)
    prev_url = None
    if dishes.has_prev:
        prev_url = url_for('cook.add_dish', page=dishes.prev_num)

    form = DishForm()
    if form.validate_on_submit():
        if form.add_entry.data:
            form.ingredients.append_entry()
        elif form.pop_entry.data:
            form.ingredients.pop_entry()
        elif form.submit.data:
            dish = Dish(name=form.dish_name.data)            
            lws_db.session.add(dish)

            for ingredient_name in form.ingredients.data:
                ingredient = Ingredient.query.filter_by(name=ingredient_name).first()
                if ingredient is None:
                    ingredient = Ingredient(name=ingredient_name)            
                    lws_db.session.add(ingredient)
                dish.add_ingredient(ingredient)

            lws_db.session.commit()
            flash('New dish is added.')
            return redirect(url_for('cook.add_dish'))

    return render_template('cook/add_dish.html', 
                            title='Dish', 
                            form=form,
                            dishes=dishes.items,
                            next_url=next_url,
                            prev_url=prev_url)

@bp.route('/add_menu', methods=['GET', 'POST'])
@login_required
def add_menu():
    page = request.args.get('page', 1, type=int)
    menus = Menu.query.paginate(page, 25, False)

    next_url = None
    if menus.has_next:
        next_url = url_for('cook.add_menu', page=menus.next_num)
    prev_url = None
    if menus.has_prev:
        prev_url = url_for('cook.add_menu', page=menus.prev_num)

    form = MenuForm(original_menu_name='')
    if form.validate_on_submit():
        if form.add_entry.data:
            form.dishes.append_entry()
        elif form.pop_entry.data:
            form.dishes.pop_entry()
        elif form.submit.data:
            menu = Menu(name=form.menu_name.data)            
            lws_db.session.add(menu)

            # add dishes that are not included in
            # dish table or menus table
            for dish_name in form.dishes.data:
                dish = Dish.query.filter_by(name=dish_name).first()
                if dish is None:
                    dish = Dish(name=dish_name)            
                    lws_db.session.add(dish)
                menu.add_dish(dish)

            lws_db.session.commit()
            flash('New menu is added.')
            return redirect(url_for('cook.add_menu'))

    return render_template('cook/add_menu.html', 
                            title='Menu', 
                            form=form,
                            menus=menus.items,
                            next_url=next_url,
                            prev_url=prev_url)

@bp.route('/edit_menu/<menu_id>', methods=['GET', 'POST'])
@login_required
def edit_menu(menu_id):
    menu = Menu.query.get(menu_id)
    if menu is None:
        flash('Menu {} not found.'.format(menu_id))
        return redirect(url_for('cook.add_menu'))

    form = MenuForm(original_menu_name=menu.name)
    if form.validate_on_submit():
        if form.add_entry.data:
            form.dishes.append_entry()
        elif form.pop_entry.data:
            form.dishes.pop_entry()
        elif form.submit.data:
            # add dishes that are not included in
            # dish table or menus table
            for dish_name in form.dishes.data:
                dish = Dish.query.filter_by(name=dish_name).first()
                if dish is None:
                    dish = Dish(name=dish_name)            
                    lws_db.session.add(dish)
                menu.add_dish(dish)

            # remove dishes that are removed via the form
            dishes_to_rm = []
            for dish in menu.dishes:
                if dish.name not in form.dishes.data:
                    dishes_to_rm.append(dish)
            for dish in dishes_to_rm:
                menu.remove_dish(dish)

            lws_db.session.commit()
            flash('New menu is modified.')
            return redirect(url_for('cook.add_menu'))
    elif request.method == 'GET':
        form.menu_name.data = menu.name
        form.dishes.pop_entry()
        for dish in menu.dishes:
            form.dishes.append_entry(dish.name)

    return render_template('cook/edit_menu.html', 
                           title='Edit Menu', 
                           form=form)

@bp.route('/summarize_menu/<menu_id>')
@login_required
def summarize_menu(menu_id):

    menu = Menu.query.get(menu_id)
    if menu is None:
        flash('Menu {} not found.'.format(menu_id))
        return redirect(url_for('cook.add_menu'))

    ingredients = menu.get_ingredients()
    return render_template('cook/view_menu.html', 
                           title='Menu Summary',
                           menu=menu,
                           ingredients=ingredients)

@bp.route('/ingredients')
@login_required
def ingredients():
    ingredients = Ingredient.query.all()
    ingredient_names = [i.name for i in ingredients]
    return jsonify(ingredient_names)

@bp.route('/dishes')
@login_required
def dishes():
    dishes = Dish.query.all()
    dish_names = [i.name for i in dishes]
    return jsonify(dish_names)

@bp.route('/menus')
@login_required
def menus():
    menus = Menu.query.all()
    menu_names = [i.name for i in menus]
    return jsonify(menu_names)

lws/templates/cook/_dish.html
<table class="table table-hover">
    <tr>
        <td>
        	<a href="https://www.google.com/search?q={{dish.name}}">
        	{{dish.name}}
        	</a>
        </td>
    </tr>
</table>

lws/templates/cook/_ingredient.html
<table class="table table-hover">
    <tr>
        <td>
        	<a href="https://www.google.com/search?q={{ingredient.name}}">
        	{{ingredient.name}}
        	</a>
        </td>
    </tr>
</table>

lws/templates/cook/_menu.html
<table class="table table-hover">
    <tr>
        <td class="col-md-4">
        	{{menu.name}}
        </td>
        <td class="col-md-4">
        	<a href="{{url_for('cook.edit_menu', menu_id=menu.id)}}">
        	Edit
        	</a><a href="{{url_for('cook.summarize_menu', menu_id=menu.id)}}">
        </td>
        <td class="col-md-4">
        	<a href="{{url_for('cook.summarize_menu', menu_id=menu.id)}}">
        	Summary
        	</a>
        </td>
    </tr>
</table>

lws/templates/cook/add_dish.html
{% extends "cook/cook_base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Add a dish</h1>
    <form class="form form-horizontal" method="post" role="form">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        {{ wtf.form_field(form.dish_name) }}
        {% for ingredient in form.ingredients %}
            {{ wtf.form_field(ingredient) }}
        {% endfor %}
        {{ wtf.form_field(form.pop_entry) }}
        {{ wtf.form_field(form.add_entry) }}
        {{ wtf.form_field(form.submit) }}
    </form>
    <br>
    {% for dish in dishes %}
    	{% include 'cook/_dish.html' %}    
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer dishes
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older dishes <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function(){
        ingredients_api_endpoint = "{{ url_for('cook.ingredients') }}";
        dishes_api_endpoint = "{{ url_for('cook.dishes') }}";

        $("input[id^='ingredients-']").autocomplete({
            source: load_items(ingredients_api_endpoint),
            });
        $("input[id='dish_name']" ).autocomplete({
            source: load_items(dishes_api_endpoint), 
            });
        });

    </script>
{% endblock %}

lws/templates/cook/add_ingredient.html
{% extends "cook/cook_base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Add an ingredient</h1>
    {{ wtf.quick_form(form) }}
    <br>
    {% for ingredient in ingredients %}
    	{% include 'cook/_ingredient.html' %}    
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer ingredients
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older ingredients <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function(){
        ingredients_api_endpoint = "{{ url_for('cook.ingredients') }}";

        $("input[id='ingredient_name']" ).autocomplete({
            source: load_items(ingredients_api_endpoint), 
            });
        }); 
    </script>
{% endblock %}

lws/templates/cook/add_menu.html
{% extends "cook/cook_base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Add a menu</h1>
    <form class="form form-horizontal" method="post" role="form">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        {{ wtf.form_field(form.menu_name) }}
        {% for dish in form.dishes %}
            {{ wtf.form_field(dish) }}
        {% endfor %}
        {{ wtf.form_field(form.pop_entry) }}
        {{ wtf.form_field(form.add_entry) }}
        {{ wtf.form_field(form.submit) }}
    </form>
    <br>
    {% for menu in menus %}
    	{% include 'cook/_menu.html' %}    
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer menus
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older menus <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function(){
        dishes_api_endpoint = "{{ url_for('cook.dishes') }}";
        menus_api_endpoint = "{{ url_for('cook.menus') }}";

        $("input[id^='dishes-']").autocomplete({
            source: load_items(dishes_api_endpoint),
            });
        $("input[id='menu_name']" ).autocomplete({
            source: load_items(menus_api_endpoint), 
            });
        });

    </script>
{% endblock %}

lws/templates/cook/cook_base.html
{% extends "base.html" %}

{% block scripts %}
    {{ super() }}
    <link href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" ></script>
    <script src="{{ url_for('static', filename='lws.js') }}" ></script>
{% endblock %}

lws/templates/cook/edit_menu.html
{% extends "cook/cook_base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Edit a menu</h1>
    <form class="form form-horizontal" method="post" role="form">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens="only") }}

        {{ wtf.form_field(form.menu_name) }}
        {% for dish in form.dishes %}
            {{ wtf.form_field(dish) }}
        {% endfor %}
        {{ wtf.form_field(form.pop_entry) }}
        {{ wtf.form_field(form.add_entry) }}
        {{ wtf.form_field(form.submit) }}
    </form>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function(){
        dishes_api_endpoint = "{{ url_for('cook.dishes') }}";
        menus_api_endpoint = "{{ url_for('cook.menus') }}";

        $("input[id^='dishes-']").autocomplete({
            source: load_items(dishes_api_endpoint),
            });
        $("input[id='menu_name']" ).autocomplete({
            source: load_items(menus_api_endpoint), 
            });
        });

    </script>
{% endblock %}

lws/templates/cook/view_menu.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Summary of {{ menu.name }}!</h1>
    <br>
    {% for ingredient in ingredients %}
    	{% include 'cook/_ingredient.html' %}    
    {% endfor %}
{% endblock %}