lws/lightcom/__init__.py
from flask import Blueprint

bp = Blueprint('lightcom', __name__)

from lws.lightcom import routes

lws/lightcom/routes.py
import os
from flask_login import login_required
from flask import render_template, flash, redirect, url_for

from lws.lightcom import bp
from lws.lightcom.publish import publish_msg

consumers = os.environ.get('MQ_CONSUMERS').split(':')

@bp.route('/', methods=['GET', 'POST'])
@login_required
def main():

    return render_template('lightcom/lightcom.html', 
                            title='Lightcom')

@bp.route('/at_home', methods=['GET'])
@login_required
def at_home():
    for consumer in consumers:
        publish_msg('turn_on_green', 'MQ_{0}'.format(consumer))
        publish_msg('turn_off_red', 'MQ_{0}'.format(consumer))
        publish_msg('turn_off_blue', 'MQ_{0}'.format(consumer))
    flash('At-Home Message is published.')
    return redirect(url_for('lightcom.main'))

@bp.route('/at_work', methods=['GET'])
@login_required
def at_work():
    for consumer in consumers:
        publish_msg('turn_on_red', 'MQ_{0}'.format(consumer))
        publish_msg('turn_off_green', 'MQ_{0}'.format(consumer))
        publish_msg('turn_off_blue', 'MQ_{0}'.format(consumer))
    flash('At-Work Message is published.')
    return redirect(url_for('lightcom.main'))

@bp.route('/on_the_way', methods=['GET'])
@login_required
def on_the_way():
    for consumer in consumers:
        publish_msg('turn_off_red', 'MQ_{0}'.format(consumer))
        publish_msg('turn_off_green', 'MQ_{0}'.format(consumer))
        publish_msg('turn_on_blue', 'MQ_{0}'.format(consumer))
    flash('On-The-Way Message is published.')
    return redirect(url_for('lightcom.main'))

lws/templates/lightcom/lightcom.html
{% extends "base.html" %}

{% block app_content %}
    <h1>LightCom</h1>
    <a class="btn btn-success btn-lg" href="{{ url_for('lightcom.at_home') }}" role="button">I'm Home</a>
    <a class="btn btn-primary btn-lg" href="{{ url_for('lightcom.on_the_way') }}" role="button">On the way</a>
    <a class="btn btn-danger btn-lg" href="{{ url_for('lightcom.at_work') }}" role="button">I'm at work</a>
{% endblock %}